version: "3.7"

services:
  plantala-app:
    container_name: plantala-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    restart: always

  plantala-media-data:
    container_name: plantala-media-data
    image: danielgatis/rembg
    volumes:
      - ./public/images:/rembg
    command: "p ./input ."
