export const mediaData = {
  isMaaS: false,
  elementSuffix: '.webp',
  colors: {
    primaryColor: '',
    secondaryColor: '',
    backgroundColor: '',
    textColor: '',
    errorColor: '',
    infoColor: '',
    successColor: '',
  },
  images: [
    {
      name:'Gefleckter Schierling - Conium maculatum',
      shortName:'Gefleckter Schierling',
      source: 'Aethusa',
      description:'Wusstest du, dass der Gefleckte Schierling zu den giftigsten heimischen Pflanzenarten gehört? Früher tötete man Menschen durch den "Schierlingsbecher" - einen hochgiftigen Trank aus Teilen der Pflanze. So starb zum Beispiel der Philosoph Sokrates.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_457146/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_457146/manifest/',
    },
    {
      name:'Chinarindenbaum - Cinchona Calisaya',
      shortName:'Chinarindenbaum',
      source: 'Cinchona_b',
      description: 'Mit China haben die Chinarindenbäume nichts zu tun. Ihr Name kommt von dem Stoff Chinin, der aus einigen von ihnen gewonnen wird. Die Bäume wachsen vor allem in Peru und Bolivien. Daher befindet sich eine der Pflanzen im Wappen von Peru.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461284/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461284/manifest/',
    },
    {
      name:'Kolabaum - Cola acuminata',
      shortName:'Kolabaum',
      source: 'Cola_a',
      description: 'Kola stinkt? Das vielleicht nicht, aber botanisch gesehen gehören die Kolabäume zur Familie der Stinkbaumgewächse. Sie stammen aus dem südlichen Afrika wurden früher vor allem wegen ihrer Früchte angebaut. Was meinst du, wurde damit gemacht?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461342/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461342/manifest/',
    },
    {
      name:'Schönblühende Kautschukliane - Landolphia comorensis',
      shortName:'Kautschukliane',
      source: 'Landolphia_b',
      description: 'Zur Pflanzenfamilie der Landolphia gehören verschiedene Arten, die Naturkautschuk absondern, wenn ihre Borke verletzt wird. Wirtschaftlich wird aber fast ausschließlich Kautschuk des Kautschukbaums genutzt, der mit den Landolphia nicht verwandt ist. Die Landolphia-Arten sind vor allem im tropischen Afrika beheimatet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461359/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461359/manifest/',
    },
    {
      name:'Ebenholzbaum - Diospyros',
      shortName:'Ebenholzbaum',
      source: 'Diospyros_b',
      description: 'Die Gattung Ebenholzbäume, die auch als Dattel- und Götterpflaumen bezeichnet werden,enthält mehrere Arten, deren Holz als "Ebenholz" für die Möbelproduktion verwendet wird. Der durch Carl von Linné aufgestellte Gattungsname Diospyros bedeutet soviel wie „Frucht des Zeus“ oder „göttliche Frucht“. Der Name leitet sich vom Kakibaum ab, der ebenfalls zu dieser Gattung gehört und für seine essbaren gleichnamigen Früchte bekannt ist.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461351/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461351/manifest/',
    },
    {
      name:'Ananas - Ananas comosus oder Ananas sativus',
      shortName:'Ananas',
      source: 'Ananas',
      description: 'Die Pflanzenart Ananas gehört zur Familie der Bromeliengewächse. Das Wort Ananas leitet sich vom Wort "naná" (Frucht) aus der Guaraní-Sprache ab, die in Teilen des nördlichen Südamerikas gesprochen wird, wo die Pflanze heimisch ist. Heute wird sie weltweit als Obstpflanze angebaut.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461320/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461320/manifest/',
    },
    {
      name:'Erdnuss - Arachis hypogaea Linné',
      shortName:'Erdnuss',
      source: 'Arachis',
      description: 'Der Name "Arachis" wurde 1753 zum ersten Mal von Carl von Linné veröffentlicht und trägt deshalb im europäischen Raum seinen Namenszusatz. Botanisch gesehen gehört die Frucht der Erdnuss zu den Hülsenfrüchten (Linsen, Bohnen, etc.), hat aber eine ähnliche Konsistenz wie Nüsse. Daher auch der englische Name "peanut" (wortwörtlich "Erbsennuss"). Es gibt ungefähr 80 Erdnuss-Arten, die ursprünglich nur in Mittel- und Südamerika vorkamen. Heute gilt China als größte Anbauregion.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461334/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461334/manifest/',
    },
    {
      name:'Brechnussbaum - Strychnos nux vomica',
      shortName:'Gewöhnliche Brechnuss',
      source: 'Brechnussbaum',
      description: 'Die Gewöhnliche Brechnuss wird u.a. auch als Krähenaugenbaum oder Strychninbaum bezeichnet. Rinde, Holz, Wurzeln, Blätter und Samen enthalten unter anderem die hochgiftige Substanz Strychnin. Der Brechnusssamen ist dabei die wesentliche Quelle für die Nervengifte Strychnin, Brucin, Colubrin und Vomicin, die als Extrakt bewirken eine Lähmung des Zentralnervensystems bewirken.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461968/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461968/manifest/',
    },
    {
      name:'Karitébaum - Butyrospermum parkii',
      shortName:'Karitébaum',
      source: 'Butterbaum',
      description: 'Der Karitébaum wird auch Sheanussbaum oder Afrikanischer Butterbaum genannt. Die in den Beerenfrüchten enthaltenen Fruchtkerne werden Kariténüsse genannt und sind eine bekannte Quelle für Speise- und Hautpflegefett, wie z.B. die Sheabutter. Das Fruchtfleisch ist essbar. Der größte Produzent von Kariténüssen ist Nigeria.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_459313/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_459313/manifest/',
    },
    {
      name:'Indischer Butterbaum - Madhuca longifolia',
      shortName:'Indischer Butterbaum',
      source: 'Butyrospermum_c',
      description: 'Der indische Butterbaum hat unzählige Bezeichnungen, wie z.B. Mowra, Mahua, Mahwabaum, Gallertbaum und Illipé. Er ist ein immergrünes Sapotengewächs, das in Indien, Nepal, Sri Lanka und Bangladesch vorkommt. Die Samen liefern ein Pflanzenfett, das ähnlich wie Kakaobutter verwendet wird. Die Blüten werden u.a. zur Essig- und Likörherstellung verwendet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461349/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461349/manifest/',
    },
    {
      name:'Spanischer Pfeffer - Capsicum annuum',
      shortName:'Spanischer Pfeffer',
      source: 'Capsicum_a',
      description: 'Die auch als Paprika bekannte Pflanzenart besitzt keine allgemein anerkannte Systematik. Man unterscheidet wahlweise zwischen Wild- und Kultursorten, gruppiert aber auch anhand der Fruchtform und -farbe. Die Gruppe Capsicum logum zeichnet sich durch lange, gebogene Früchte aus, die in Büscheln wachsen. Die Bandbreite an Schärfegraden in dieser Pflanzenart ist sehr groß und reicht von mildem Gemüsepaprika bis hin zu würzigem Chayennepfeffer und scharfen Chilis.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461353/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461353/manifest/',
    },
    {
      name:'Arabica-Kaffee - Coffea arabica Linné',
      shortName:'Arabica-Kaffee',
      source: 'Coffea',
      description: 'Der Arabica-Kaffee wird auch Bergkaffee oder Javakaffee genannt. Die Pflanze wächst Baum- oder Strauchförmig und bildet als Früchte die sogenannten "Kaffeekirschen" aus. Die Kaffeekirsche ist eine rote Steinfrucht, deren Samen die Kaffeebohnen darstellen. Durch Trocknung und Röstung entwickeln diese ein starkes Aroma. Daher wird sie inzwischen weltweit (neben der Sorte Robusta) zur Kaffeeproduktion genutzt.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461269/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461269/manifest/',
    },
    {
      name:'Edelkastanie - Castanea sativa',
      shortName:'Edelkastanie',
      source: 'Castanea',
      description: 'Die Edelkastanie wird auch als Esskastanie bezeichnet. Mit der in Europa verbreiteten Rosskastanie hat sie botanisch wenig zu tun. Allein die äußerliche Ähnlichkeit trug dazu bei, dass sie in der deutschen Sprache einen gleichklingenden NAmen trägt. Die auch als Maronen oder Maroni bezeichneten Früchte der Edelkastanie sind essbar. Sie werden u.a. geröstet auf Märkten angeboten. Man kann aber auch Mehl und Püree daraus herstellen.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461959/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461959/manifest/',
    },
    {
      name:'Chinarindenbaum - Cinchona Calisaya',
      shortName:'Chinarindenbaum',
      source: 'Cinchona_a',
      description: 'Du denkst, der Chinarindenbaum hat mit China zu tun? Falsch gedacht! Einige der zur Gattung gehörenden Pflanzen werden zur Chinin-Gewinnung genutzt, das z.B. zur Malariabekämpfung eingesetzt wird. Daher nennt man sie auch Fieberrindenbäume.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461284/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461284/manifest/',
    },
    {
      name:'Karitébaum - Butyrospermum parkii',
      shortName:'Karitébaum',
      source: 'Butyrospermum_a',
      description: 'Der Karitébaum wird auch Sheanussbaum oder Afrikanischer Butterbaum genannt. Die in den Beerenfrüchten enthaltenen Fruchtkerne werden Kariténüsse genannt und sind eine bekannte Quelle für Speise- und Hautpflegefett, wie z.B. die Sheabutter. Das Fruchtfleisch ist essbar. Der größte Produzent von Kariténüssen ist Nigeria.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461349/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461349/manifest/',
    },
    {
      name:'Kolabaum - Cola acuminata',
      shortName:'Kolabaum',
      source: 'Cola_b',
      description: 'Kolabäume werden wegen ihrer Früchte, den „Kolanüssen“, angebaut. Diese enthalten u.a. Koffein, was bekanntlich wach macht. Wie du vermutlich schon geahnt hast, wurde aus den Nüssen früher wirklich das Aroma für Colagetränke gewonnen. Und heute?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461342/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461342/manifest/',
    },
    {
      name:'Ackerwinde - Convolvulus arvensis',
      shortName:'Ackerwinde',
      source: 'Convolvulus',
      description: 'Die Ackerwinde ist eine in Europa weitverbreitete Pflanzengattung, die neben Äckern auch auf Wiesen, Wegen und Schuttplätzen zu finden ist. Sie wird traditionell als Heilpflanze bei Herzkreislauferkrankungen eingesetzt. Außerdem enthält sie psychoaktive Stoffe, die nach altem Aberglauben von vermeintlichen "Hexen" in Salben verwendet worden sein sollen.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_457144/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_457144/manifest/',
    },
    {
      name:'Muskatnussbaum - Myristica fragrans',
      shortName:'Muskatnussbaum',
      source: 'Myristica_b',
      description: 'Der vor allem in den Tropen angebaute Muskatnussbaum ist ein immergrünes Gewächs, das für seine Samen bekannt ist. Die Samen werden als Muskatnüsse bezeichnet und dienen vor allem als Gewürzmittel. Das Wort Muskat leitet sich aus dem Französischen ab und bedeutet so viel wie „nach Moschus duftende Nuss“. In sehr hohen Dosen treten beim Genuss von Muskat Rauscherscheinungen und Brechreiz auf.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461280/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461280/manifest/',
    },
    {
      name:'Yams - Dioscorea',
      shortName:'Yams',
      source: 'Dioscorea',
      description: 'Yams oder auch Yamswurzel ist eine in den Tropen verbreitete Pflanzengattung. Je nach spezifischer Yamsart werden Teile der Pflanze als Heilpflanze oder auch als Lebensmittel verwendet. Die essbaren Wurzelknollen schmecken ähnlich wie Kartoffeln oder Esskastanien. Während man in Europa selten Yamswurzeln kaufen kann, gehören sie in Südamerika, Afrika und der Karibik zum alltäglichen Gemüseangebot.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461952/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461952/manifest/',
    },
    {
      name:'Muskatnussbaum - Myristica fragrans',
      shortName:'Muskatnussbaum',
      source: 'Myristica_c',
      description: 'Der vor allem in den Tropen angebaute Muskatnussbaum ist ein immergrünes Gewächs, das für seine Samen bekannt ist. Die Samen werden als Muskatnüsse bezeichnet und dienen vor allem als Gewürzmittel. Das Wort Muskat leitet sich aus dem Französischen ab und bedeutet so viel wie „nach Moschus duftende Nuss“. In sehr hohen Dosen treten beim Genuss von Muskat Rauscherscheinungen und Brechreiz auf.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461280/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461280/manifest/',
    },
    {
      name:'Ebenholzbaum - Diospyros',
      shortName:'Ebenholzbaum',
      source: 'Diospyros_a',
      description: 'Die Gattung Ebenholzbäume, die auch als Dattel- und Götterpflaumen bezeichnet werden,enthält mehrere Arten, deren Holz als "Ebenholz" für die Möbelproduktion verwendet wird. Der durch Carl von Linné aufgestellte Gattungsname Diospyros bedeutet soviel wie „Frucht des Zeus“ oder „göttliche Frucht“. Der Name leitet sich vom Kakibaum ab, der ebenfalls zu dieser Gattung gehört und für seine essbaren gleichnamigen Früchte bekannt ist.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461351/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461351/manifest/',
    },
    {
      name:'Ölpalme - Elaeis guineensis',
      shortName:'Ölpalme',
      source: 'Elaeis',
      description: 'Die Ölpalme ist eine wirtschaftlich relevante Palmenart, aus deren Frucht das sogenannte Palmöl gewonnen wird. Der Samen liefert das Palmkernöl. Beide Öle werden in vielfältigsten Lebensmitteln verwendet (z.B. in Süßwaren). Problematisch ist der extensive Anbau von Ölpalmenplantagen, da dafür oft Regenwald gerodet wird und durch Ölpalmenmonokulturen ersetzt wird. ',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461298/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461298/manifest/',
    },
    {
      name:'Lokustbaum - Hymenaea courbaril',
      shortName:'Lokustbaum',
      source: 'Hymenaea_a',
      description: 'Für die zu den Johannisbrotbaumgewächsen zählende Pflanzengattung Hymenaea werden vielfältige Namen verwendet: Animebäume, Südamerikanische Kirschen, Brasilkirschen, Heuschreckenbäume und Lokusbäume. Hymenaea courbaril gedeiht von Südamerika bis Mexiko. Die Frucht wird u.a. zur Herstellung von Alkoholika verwendet, die Rinde dient als Tee oder Arznei und das Harz wird für Lacke verwendet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461325/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461325/manifest/',
    },
    {
      name:'Johanniskrautgewächse - Hypericum ascyron',
      shortName:'Johanniskraut',
      source: 'Hypericaceae',
      description: 'Der Name des Joahhniskrauts bezieht sich auf die biblische Gestalt von Johannes dem Täufer, da die Pflanze um den Johannistag (24. Juni) herum blüht. In Europa ist diese Art der Johanniskrautgewächse am weitesten verbreitet und wird aufgrund ihrer medizinischen Wirkung landwirtschaftlich angebaut. Es wird vor allem als am häufigsten als Beruhigungsmittel und Antidepressivum verwendet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456951/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456951/manifest/',
    },
    {
      name:'Karitébaum - Butyrospermum parkii',
      shortName:'Karitébaum',
      source: 'Butyrospermum_b',
      description: 'Der Karitébaum wird auch Sheanussbaum oder Afrikanischer Butterbaum genannt. Die in den Beerenfrüchten enthaltenen Fruchtkerne werden Kariténüsse genannt und sind eine bekannte Quelle für Speise- und Hautpflegefett, wie z.B. die Sheabutter. Das Fruchtfleisch ist essbar. Der größte Produzent von Kariténüssen ist Nigeria.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461349/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461349/manifest/',
    },
    {
      name:'Indigopflanze - Indigofera tinctoria',
      shortName:'Indigopflanze',
      source: 'Indigofera',
      description: 'Die Indigopflanze, die vor allem in Indien, den tropischen Regionen Afrikas sowie in China vorkommt, wurde mehrheitlich für die Gewinnung des Indigos genutzt. Indigo ist ein dunkelblauer Farbstoff, der zum Färben von Bekleidung verwendet wurde. Heute wird dieser Stoff in der Regel synthetisch hergestellt. Die getrockneten und gemahlenen Blätter dienen auch als Haarfärbemittel.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461962/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461962/manifest/',
    },
    {
      name:'Kokospalme - Cocos nucifera',
      shortName:'Kokospalme',
      source: 'Kokospalme',
      description: 'Kokospalmen sind sehr alte Kulturpflanzen und werden bereits seit mindestens 3000 Jahren angebaut. Das Wort Kokos geht auf das altgriechische Wort kókkos zurück, was so viel wie „Kern“ oder „Beere“ bedeutet. Die Früchte der Kokospalme werden Kokosnüsse genannt und ihre Bestandteile als Saft oder andere Nahrungsmittel verwendet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_463209/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_463209/manifest/',
    },
    {
      name:'Schönblühende Kautschukliane - Landolphia comorensis',
      shortName:'Kautschukliane',
      source: 'Landolphia_a',
      description: 'Zur Pflanzenfamilie der Landolphia gehören verschiedene Arten, die Naturkautschuk absondern, wenn ihre Borke verletzt wird. Wirtschaftlich wird aber fast ausschließlich Kautschuk des Kautschukbaums genutzt, der mit den Landolphia nicht verwandt ist. Die Landolphia-Arten sind vor allem im tropischen Afrika beheimatet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461359/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461359/manifest/',
    },
    {
      name:'Westindisches Mahagoni - Swietenia mahagoni',
      shortName:'Westindisches Mahagoni',
      source: 'Mahagonibaum',
      description: 'Das Westindische Mahagoni kommt im Süden Floridas sowie auf den karibischen Inseln vor und steht auf der Liste stark gefährdeter Arten. Mahagoniholz wird gern für dekorative Furniere beim Möbelbau verwendet. Aufgrund seines halb- bis immergrünen Erscheinungswesen sowie der Toleranz gegenüber Trockenheit wurde er gern für die Bepflanzung von Straßenrändern eingesetzt.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_463203/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_463203/manifest/',
    },
    {
      name:'Maniok - Manihot esculenta',
      shortName:'Maniok',
      source: 'Manihot',
      description: 'Maniok, der je nach Sprachraum auch als Kassave oder Yuca bezeichnet wird, ist eine aus Südamerika stammende Pflanzenart. Die aus der Wurzelknolle gewonnene Stärke wird Tapioka genannt und zur Ernährung verwendet. In rohem Zustand sind die Maniok-Knollen giftig, sodass sie vor der Verwendung verarbeitet werden müssen, z.B. durch Fermentation oder Erhitzung.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461287/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461287/manifest/',
    },
    {
      name:'Spanischer Pfeffer - Capsicum annuum',
      shortName:'Spanischer Pfeffer',
      source: 'Capsicum_b',
      description: 'Die auch als Paprika bekannte Pflanzenart besitzt keine allgemein anerkannte Systematik. Man unterscheidet wahlweise zwischen Wild- und Kultursorten, gruppiert aber auch anhand der Fruchtform und -farbe. Die Gruppe Capsicum logum zeichnet sich durch lange, gebogene Früchte aus, die in Büscheln wachsen. Die Bandbreite an Schärfegraden in dieser Pflanzenart ist sehr groß und reicht von mildem Gemüsepaprika bis hin zu würzigem Chayennepfeffer und scharfen Chilis.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461353/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461353/manifest/',
    },
    {
      name:'Pfeilwurz - Maranta arundinacea',
      shortName:'Pfeilwurz',
      source: 'Maranta',
      description: 'Der Name Pfeilwurz bezeichnet sowohl Pflanzenart als auch die übergeordnete Gattung. Aus Maranta arundinacea wird das Pfeilwurzmehl gewonnen, das traditionell als Auszuggmittel für vergiftete Wunden genutzt wurde. Das auch als Arrow Root bezeichnete Stärkemehl wird weltweit als leichtverdauliche Weizenmehlalternative vermarktet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461954/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461954/manifest/',
    },
    {
      name:'Teepflanze - Camellia sinensis',
      shortName:'Teepflanze',
      source: 'Thea',
      description: '1753 veröffentlichte Carl von Linné die Teepflanze erstmals für den europäischen Raum unter dem Namen "Thea sinensis". Aus den Blättern der Pflanze wird je nach Stadium und Weiterverarbeitungsart grüner oder schwarzer Tee zubereitet. Schwarzem Tee wird durch den Gehalt an Coffein eine anregende Wirkung zugesprochen. Grüner Tee soll günstig gegen freie Radikale wirken.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461270/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461270/manifest/',
    },
    {
      name:'Dessertbanane - Musa sapientium',
      shortName:'Dessertbanane',
      source: 'Musa',
      description: 'Die Bananenpflanze stammt ursprünglich aus Südostasien und wurde in religiösen Quellen bereits vor mehr als 2000 Jahren erwähnt. Im deutschsprachigen Raum ist die Dessertbanane heute eine der meistgegessenen importierten Obstsorten. Der aus dem Portugiesischen eingedeutschte Begriff "Banane" löste seit dem Anfang des 19. Jahrhunderts ältere Bezeichnungen wie z.B. „Paradiesfeige“ ab.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461955/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461955/manifest/',
    },
    {
      name:'Muskatnussbaum - Myristica fragrans',
      shortName:'Muskatnussbaum',
      source: 'Myristica_a',
      description: 'Der vor allem in den Tropen angebaute Muskatnussbaum ist ein immergrünes Gewächs, das für seine Samen bekannt ist. Die Samen werden als Muskatnüsse bezeichnet und dienen vor allem als Gewürzmittel. Das Wort Muskat leitet sich aus dem Französischen ab und bedeutet so viel wie „nach Moschus duftende Nuss“. In sehr hohen Dosen treten beim Genuss von Muskat Rauscherscheinungen und Brechreiz auf.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461280/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461280/manifest/',
    },
    {
      name:'Kolabaum - Cola acuminata',
      shortName:'Kolabaum',
      source: 'Cola_c',
      description: 'Die Nüsse der Kolabäume werden heute nur noch selten für die Gewinnung von Aromen für Colagetränken genutzt. Inzwischen erzeugt man den Geschmack meist chemisch. Sie werden aber noch für Lebensmittelfarbe und Medizin verwendet. Auch gut, oder?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461342/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461342/manifest/',
    },
    {
      name:'Lokustbaum - Hymenaea courbaril',
      shortName:'Lokustbaum',
      source: 'Hymenaea_b',
      description: 'Für die zu den Johannisbrotbaumgewächsen zählende Pflanzengattung Hymenaea werden vielfältige Namen verwendet: Animebäume, Südamerikanische Kirschen, Brasilkirschen, Heuschreckenbäume und Lokusbäume. Hymenaea courbaril gedeiht von Südamerika bis Mexiko. Die Frucht wird u.a. zur Herstellung von Alkoholika verwendet, die Rinde dient als Tee oder Arznei und das Harz wird für Lacke verwendet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461325/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461325/manifest/',
    },
    {
      name:'Steinnusspalme - Phytelephas macrocarpa',
      shortName:'Steinnusspalme',
      source: 'Phytelephas',
      description: 'Die Gattung der Steinnusspalmen, auch Elfenbeinpalmen genannt, sind in Süd- und Zentralamerika beheimatet. Ein Teil des Samens der Pflanze wird als pflanzlicher Elfenbeinersatz verwendet. Normalerweise wird als Elfenbein die Zahnsubstanz der Stoßzähne von Elefanten (und Mammuts) bezeichnet. Das Endosperm des Samens der Steinnusspalme ist in getrocknetem Zustand ebenso hart und wird für Schnitzwerk verwendet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461318/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461318/manifest/',
    },
    {
      name:'Piment - Pimenta officinalis',
      shortName:'Piment',
      source: 'Pimenta',
      description: 'Piment, auch als Nelkenpfeffer bezeichnet, gehört zur Familie der Myrtengewächse. Die immergrünen Pflanzen kommen vor allem in Zentralamerika und der Karibik vor. Als Gewürz werden die unreifen Früchte verwendet. Während in der Karibik Piment ein fester Bestandteil der Alltagsküche ist, wird es in Deutschland mehrheitlich zur Wurstherstellung und in der Weihnachtsbäckerei eingesetzt.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461277/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461277/manifest/',
    },
    {
      name:'Spiegelndes Laichkraut - Potamogeton lucens',
      shortName:'Spiegelndes Laichkraut',
      source: 'Potamogetonaceae',
      description: 'Das Spiegelnde Laichkraut ist eine Wasserpflanze, die unter der Wasseroberfläche wächst. Nur die Blüten schauen während der Blütezeit aus dem Wasser hervor, da die Bestäubung durch den Wind erfolgt. Das Spiegelnde Laichkraut wächst in nährstoffreichen, stehenden oder langsam fließenden Gewässern in Teilen Ostasiens und Europas in Tiefen von 1,5 bis 3,0 Metern.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456939/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456939/manifest/',
    },
    {
      name:'Echte Dattelpalme - Phoenix dactylifera',
      shortName:'Echte Dattelpalme',
      source: 'Phoenix',
      description: 'Bei der echten Dattelpalme handelt es sich um eine alte Kulturpflanze, deren Nutzung sich bis in die Antike zurückverfolgen lässt. Als Wüstenpflanze benötigt sie viel Sonne, aber auch Wasser. Weshalb sie vor allem in der Region Mesopotamiens ihren Ursprung hat. Ihre süßen Früchte werden Datteln genannt und konservieren sich aufgrund ihres ohen Zuckergehalts im trocken-heißen Klima der Anbauländer von selbst.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461946/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461946/manifest/',
    },
    {
      name:'Kampferbaum - Cinnamomum camphora',
      shortName:'Kampferbaum',
      source: 'Cinnamomum',
      description: 'Der Kampferbaum, auch als Kampferlorbeer bezeichnet, zählt zur Familie der Lorbeergewächse. Der immergrüne Baum stammt aus Ostasien, wird aber inzwischen auch u.a. in Brasilien angebaut und gilt in einigen anderen Teilen der Welt als invasive Art. Insbesondere aus dem Holz des Baumes wird Campheröl gewonnen, das als Medizin genutzt wird.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461324/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461324/manifest/',
    },
    {
      name:'Waldmeister  - Galium odoratum',
      shortName:'Waldmeister',
      source: 'Rubiaceae',
      description: 'Der Waldmeister, auch Maikraut genannt, wächst oft in den Laubwäldern Europas und Asiens. Aufgrund seines charakteristischen Geschmacks wird er als Würzkraut verwendet, z.B. für Waldmeisterbowle oder auch für Sirups. Der Geschmack kommt durch den Pflanzenstoff Cumarin zustande. Heutzutage wird Waldmeisteraroma für die Lebensmittelindustrie oft synthetisch hergestellt.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456904/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456904/manifest/',
    },
    {
      name:'Olivenbaum - Olea europaea',
      shortName:'Olivenbaum',
      source: 'Oleaceae',
      description: 'Der Olivenbaum wird auch Echter Ölbaum genannt. Seit mehr als Er wird seit rund 6000 Jahren als Nutzpflanze kultiviert und wächst als immergrüner Baum oder Strauch insbesondere im Mittelmeerraum und dem Nahen Osten. Aus den Früchten des Baumes, Oliven genannt, wird mehrheitlich Speiseöl gepresst. Die Oliven selbst sind roh nicht essbar und werden daher durch mehrfaches Einlegen genießbar gemacht.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456931/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456931/manifest/',
    },
  ],
};
