export const mediaData = {
  isMaaS: false,
  colors: {
    primaryColor: '',
    secondaryColor: '',
    backgroundColor: '',
    textColor: '',
    errorColor: '',
    infoColor: '',
    successColor: '',
  },
  images: [
    {
      name:'Gefleckter Schierling',
      shortName:'Gefleckter Schierling',
      source: 'Aethusa',
      description:
        'Definition: Giftpflanze die in der Antike für den Schierlingsbecher verwendet wurde; Doldengewächse',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_457146/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_457146/manifest/',
    },
    {
      name:'Ananas',
      shortName:'Ananas',
      source: 'Ananas',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461320/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461320/manifest/',
    },
    {
      name:'Erdnuss',
      shortName:'Erdnuss',
      source: 'Arachis',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461334/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461334/manifest/',
    },
    {
      name:'Brechnussbaum',
      shortName:'Brechnussbaum',
      source: 'Brechnussbaum',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461968/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461968/manifest/',
    },
    {
      name:'Frucht des Afrikanischen Butterbaums im Querschnitt',
      shortName:'Afrikanischer Butterbaum',
      source: 'Butterbaum',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_459313/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_459313/manifest/',
    },
    {
      name:'Fruchtknoten des Afrikanischen Butterbaums',
      shortName:'Afrikanischer Butterbaum',
      source: 'Butyrospermum_a',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461349/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461349/manifest/',
    },
    {
      name:'Frucht des Afrikanischen Butterbaums',
      shortName:'Afrikanischer Butterbaum',
      source: 'Butyrospermum_b',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461349/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461349/manifest/',
    },
    {
      name:'Frucht des Mahwabaums',
      shortName:'Mahwabaums',
      source: 'Butyrospermum_c',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461349/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461349/manifest/',
    },
    {
      name:'Fruchtknoten des Spanischen Pfeffers',
      shortName:'Spanischer Pfeffer',
      source: 'Capsicum_a',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461353/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461353/manifest/',
    },
    {
      name:'Fruchtquerschnitt des Spanischen Pfeffers',
      shortName:'Spanischen Pfeffer',
      source: 'Capsicum_b',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461353/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461353/manifest/',
    },
    {
      name:'Kaffeebaum',
      shortName:'Kaffeebaum',
      source: 'Coffea',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461269/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461269/manifest/',
    },
    {
      name:'Edelkastanie',
      shortName:'Edelkastanie',
      source: 'Castanea',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461959/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461959/manifest/',
    },
    {
      name:'Fruchtknotenquerschnitt des Fieberrindenbaum',
      shortName:'Fieberrindenbaum',
      source: 'Cinchona_a',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461284/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461284/manifest/',
    },
    {
      name:'Blüte des Fieberrindenbaum',
      shortName:'Fieberrindenbaum',
      source: 'Cinchona_b',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461284/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461284/manifest/',
    },
    {
      name:'Kampferbaum',
      shortName:'Kampferbaum',
      source: 'Cinnamomum',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461324/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461324/manifest/',
    },
    {
      name:'Blütenstempel des Kolabaums',
      shortName:'Kolabaum',
      source: 'Cola_a',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461342/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461342/manifest/',
    },
    {
      name:'Blütenfruchtknoten des Kolabaums',
      shortName:'Kolabaum',
      source: 'Cola_b',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461342/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461342/manifest/',
    },
    {
      name:'Einzelner Fruchtknoten des Kolabaums',
      shortName:'Kolabaum',
      source: 'Cola_c',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461342/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461342/manifest/',
    },
    {
      name:'Ackerwinde-Stechapfel',
      shortName:'Ackerwinde-Stechapfel',
      source: 'Convolvulus',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_457144/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_457144/manifest/',
    },
    {
      name:'Yams',
      shortName:'Yams',
      source: 'Dioscorea',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461952/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461952/manifest/',
    },
    {
      name:'Längsschnitt der männlichen Blüte des Ebenholzbaums',
      shortName:'Ebenholzbaum',
      source: 'Diospyros_a',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461351/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461351/manifest/',
    },
    {
      name:'Weibliche Blüte im Längsschnitt des Ebenholzbaums',
      shortName:'Ebenholzbaum',
      source: 'Diospyros_b',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461351/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461351/manifest/',
    },
    {
      name:'Afrikanische Ölpalme',
      shortName:'Afrikanische Ölpalme',
      source: 'Elaeis',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461298/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461298/manifest/',
    },
    {
      name:'Fruchtlängsschnitt des Lokustbaums',
      shortName:'Lokustbaum',
      source: 'Hymenaea_a',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461325/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461325/manifest/',
    },
    {
      name:'Blütenboden und Stempel des Lokustbaums',
      shortName:'Lokustbaum',
      source: 'Hymenaea_b',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461325/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461325/manifest/',
    },
    {
      name:'Johanniskrautgewächse',
      shortName:'Johanniskrautgewächse',
      source: 'Hypericaceae',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456951/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456951/manifest/',
    },
    {
      name:'Indigopflanze',
      shortName:'Indigopflanze',
      source: 'Indigofera',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461962/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461962/manifest/',
    },
    {
      name:'Kokospalme',
      shortName:'Kokospalme',
      source: 'Kokospalme',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_463209/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_463209/manifest/',
    },
    {
      name:'Blütenboden und Längsknoten der Schönblühenden Kautschukliane',
      shortName:'Schönblühende Kautschukliane',
      source: 'Landolphia_a',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461359/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461359/manifest/',
    },
    {
      name:'Geöffnete Frucht der Schönblühenden Kautschukliane',
      shortName:'Schönblühende Kautschukliane',
      source: 'Landolphia_b',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461359/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461359/manifest/',
    },
    {
      name:'Mahagonibaum',
      shortName:'Mahagonibaum',
      source: 'Mahagonibaum',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_463203/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_463203/manifest/',
    },
    {
      name:'Maniok- oder Cassavestrauch',
      shortName:'Maniok- oder Cassavestrauch',
      source: 'Manihot',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461287/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461287/manifest/',
    },
    {
      name:'Arrowrootpflanze',
      shortName:'Arrowrootpflanze',
      source: 'Maranta',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461954/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461954/manifest/',
    },
    {
      name:'Theestrauch',
      shortName:'Theestrauch',
      source: 'Thea',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461270/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461270/manifest/',
    },
    {
      name:'Echte Banane',
      shortName:'Echte Banane',
      source: 'Musa',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461955/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461955/manifest/',
    },
    {
      name:'Fruchtknotenlängsschnitt des Muskatnussbaums',
      shortName:'Muskatnussbaum',
      source: 'Myristica_a',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461280/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461280/manifest/',
    },
    {
      name:'Längsschnitt der Männlichen Blüte des Muskatnussbaum',
      shortName:'Muskatnussbaum',
      source: 'Myristica_b',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461280/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461280/manifest/',
    },
    {
      name:'Blütenquerschnitt des Muskatnussbaums',
      shortName:'Muskatnussbaum',
      source: 'Myristica_c',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461280/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461280/manifest/',
    },
    {
      name:'Kleinfruchtige Elfenbeinpalme',
      shortName:'Kleinfruchtige Elfenbeinpalme',
      source: 'Phytelephas',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461318/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461318/manifest/',
    },
    {
      name:'Nelkenpfeffer',
      shortName:'Nelkenpfeffer',
      source: 'Pimenta',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461277/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461277/manifest/',
    },
    {
      name:'Laichkrautgewächse',
      shortName:'Laichkrautgewächse',
      source: 'Potamogetonaceae',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456939/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456939/manifest/',
    },
    {
      name:'Dattelpalme',
      shortName:'Dattelpalme',
      source: 'Phoenix',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461946/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461946/manifest/',
    },
    {
      name:'Rötegewächse',
      shortName:'Rötegewächse',
      source: 'Rubiaceae',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456904/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456904/manifest/',
    },
    {
      name:'Ölbaumgewächse',
      shortName:'Ölbaumgewächse',
      source: 'Oleaceae',
      description: '',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456931/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456931/manifest/',
    },
  ],
};
