export const mediaData = {
  isMaaS: false,
  elementSuffix: '.webp',
  colors: {
    primaryColor: '',
    secondaryColor: '',
    backgroundColor: '',
    textColor: '',
    errorColor: '',
    infoColor: '',
    successColor: '',
  },
  images: [
    {
      name:'Gefleckter Schierling - Conium maculatum',
      shortName:'Gefleckter Schierling',
      source: 'Aethusa',
      description:'Wusstest du, dass der Gefleckte Schierling zu den giftigsten heimischen Pflanzenarten gehört? Früher tötete man Menschen durch den "Schierlingsbecher" - einem hochgiftigen Trank aus Teilen der Pflanze. So starb zum Beispiel der Philosoph Sokrates.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_457146/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_457146/manifest/',
    },
    {
      name:'Kokospalme - Cocos nucifera',
      shortName:'Kokospalme',
      source: 'Kokospalme',
      description: 'Kennst du das Lied: „Wer hat die Kokosnuss geklaut“? Kokospalmen sind sehr alte Kulturpflanzen und werden bereits seit mindestens 3000 Jahren angebaut. Das Wort Kokos geht auf das altgriechische Wort kókkos zurück, das „Kern“ oder „Beere“ bedeutet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_463209/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_463209/manifest/',
    },
    {
      name:'Chinarindenbaum - Cinchona Calisaya',
      shortName:'Chinarindenbaum',
      source: 'Cinchona_b',
      description: 'Mit China haben die Chinarindenbäume nichts zu tun. Ihr Name kommt von dem Stoff Chinin, der aus einigen von ihnen gewonnen wird. Die Bäume wachsen vor allem in Peru und Bolivien. Daher befindet sich eine der Pflanzen im Wappen von Peru.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461284/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461284/manifest/',
    },
    {
      name:'Maniok - Manihot esculenta',
      shortName:'Maniok',
      source: 'Manihot',
      description: 'Maniok (auch Kassave oder Yuca) hast du wahrscheinlich noch nie gegessen, denn in Europa kann man ihn selten kaufen. Roh sind die Wurzelknollen giftig, sodass sie vor dem Verzehr erst fermentiert oder erhitzt werden müssen.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461287/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461287/manifest/',
    },
    {
      name:'Kolabaum - Cola acuminata',
      shortName:'Kolabaum',
      source: 'Cola_a',
      description: 'Kola stinkt? Das vielleicht nicht, aber botanisch gesehen gehören die Kolabäume zur Familie der Stinkbaumgewächse. Sie stammen aus dem südlichen Afrika und wurden früher vor allem wegen ihrer Früchte angebaut. Was meinst du, wurde damit gemacht?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461342/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461342/manifest/',
    },
    {
      name:'Schönblühende Kautschukliane - Landolphia comorensis',
      shortName:'Kautschukliane',
      source: 'Landolphia_b',
      description: 'Zur Familie der Landolphia gehören verschiedene Pflanzenarten, die Naturkautschuk absondern. Weißt du denn, was Kautschuk ist? So nennt man die gummiartige Substanz im Milchsaft der Bäume, der aus der Rinde hervorquillt, wenn man diese einschneidet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461359/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461359/manifest/',
    },
    {
      name:'Ebenholzbaum - Diospyros',
      shortName:'Ebenholzbaum',
      source: 'Diospyros_b',
      description: 'Denkst du bei Ebenholz auch sofort an das Märchen von Schneewittchen? Die Gattung, deren Pflanzen auch als Dattel- und Götterpflaumen bezeichnet werden, umfasst mehrere Arten, deren Holz als "Ebenholz" für die Möbelproduktion verwendet wird.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461351/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461351/manifest/',
    },
    {
      name:'Ananas - Ananas comosus oder Ananas sativus',
      shortName:'Ananas',
      source: 'Ananas',
      description: 'Die Obstsorte Ananas kennt wohl jede:r. Aber wusstest du, dass sich das Wort Ananas vom Wort "naná" (Frucht) aus der Guaraní-Sprache ableitet? Diese wird in Teilen des nördlichen Südamerikas gesprochen, wo die Pflanze heimisch ist.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461320/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461320/manifest/',
    },
    {
      name:'Erdnuss - Arachis hypogaea Linné',
      shortName:'Erdnuss',
      source: 'Arachis',
      description: 'Du denkst, die Erdnuss ist eine Nuss? Nicht ganz. Botanisch gesehen gehört die Erdnuss zu den Hülsenfrüchten, wie Linsen oder Bohnen. Sie hat aber eine ähnliche Konsistenz wie Nüsse. Daher der englische Name "peanut" (wortwörtlich "Erbsennuss"). ',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461334/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461334/manifest/',
    },
    {
      name:'Gewöhnlicher Brechnussbaum - Strychnos nux vomica',
      shortName:'Brechnuss',
      source: 'Brechnussbaum',
      description: 'Diese Pflanze hat viele Namen, z.B. Krähenaugenbaum oder Strychninbaum. Ihre Samen enthalten die starken Nervengifte Strychnin, Brucin, Colubrin und Vomicin, die als Extrakt eine Lähmung des Zentralnervensystems bewirken. Klingt unangenehm, oder?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461968/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461968/manifest/',
    },
    {
      name:'Karitébaum - Butyrospermum parkii',
      shortName:'Karitébaum',
      source: 'Butterbaum',
      description: 'Bei Karité denkst du wahrscheinlich nicht direkt an die Sheabutter aus deiner Hautcreme. Aber genau daher kommt sie. Die Sheabutter wird aus den Fruchtkernen der Beeren des Karitébaums gewonnen. Sie wird aber auch als Speisefett verwendet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_459313/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_459313/manifest/',
    },
    {
      name:'Indischer Butterbaum - Madhuca longifolia',
      shortName:'Indischer Butterbaum',
      source: 'Butyrospermum_c',
      description: 'Alles in Butter? Man kann den Indischen Butterbaum auch Mowra, Mahwabaum oder Gallertbaum nennen. Er kommt in Indien, Nepal, Sri Lanka und Bangladesch vor. Die Samen liefern ein Pflanzenfett, das ähnlich wie Kakaobutter verwendet wird.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461349/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461349/manifest/',
    },
    {
      name:'Spanischer Pfeffer - Capsicum annuum',
      shortName:'Spanischer Pfeffer',
      source: 'Capsicum_a',
      description: 'Bei Pfeffer denkst du an schwarze Kugeln? Es handelt sich beim Spanischen Pfeffer aber um die als „Paprika“ bekannte Pflanzenart. Man unterscheidet wahlweise zwischen Wild- und Kultursorten, gruppiert aber auch anhand der Fruchtform und -farbe.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461353/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461353/manifest/',
    },
    {
      name:'Arabica-Kaffee - Coffea arabica Linné',
      shortName:'Arabica-Kaffee',
      source: 'Coffea',
      description: 'Kaffee ist klar, oder? Die Pflanze bildet die sogenannten "Kaffeekirschen" aus, deren Samen die Kaffeebohnen darstellen. Durch Trocknung und Röstung entwickeln diese ein starkes Aroma, weshalb sie weltweit zur Kaffeeproduktion genutzt werden.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461269/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461269/manifest/',
    },
    {
      name:'Edelkastanie - Castanea sativa',
      shortName:'Edelkastanie',
      source: 'Castanea',
      description: 'Hast du mal heiße Maronen gegessen? Die als Maronen bezeichneten Früchte der Edelkastanie sind essbar und geröstet sehr lecker. Mit der Rosskastanie hat die Pflanze nichts zu tun. Nur aufgrund ihres Aussehens werden sie im Deutschen ähnlich benannt.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461959/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461959/manifest/',
    },
    {
      name:'Chinarindenbaum - Cinchona Calisaya',
      shortName:'Chinarindenbaum',
      source: 'Cinchona_a',
      description: 'Du denkst, der Chinarindenbaum hat mit China zu tun? Falsch gedacht! Einige der zur Gattung gehörenden Pflanzen werden zur Chinin-Gewinnung genutzt, das z.B. zur Malariabekämpfung eingesetzt wird. Daher nennt man sie auch Fieberrindenbäume.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461284/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461284/manifest/',
    },
    {
      name:'Karitébaum - Butyrospermum parkii',
      shortName:'Karitébaum',
      source: 'Butyrospermum_a',
      description: 'Der Karitébaum wird zur Gewinnung von Sheabutter, die aus den Kernen der Kariténüsse gewonnen wird. Aber auch das Fruchtfleisch der Nüsse ist essbar. Heutzutage ist Nigeria einer der größten Produzenten von Kariténüssen. Wusstest du das?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461349/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461349/manifest/',
    },
    {
      name:'Kolabaum - Cola acuminata',
      shortName:'Kolabaum',
      source: 'Cola_b',
      description: 'Kolabäume werden wegen ihrer Früchte, den „Kolanüssen“, angebaut. Diese enthalten u.a. Koffein, was bekanntlich wach macht. Wie du vermutlich schon geahnt hast, wurde aus den Nüssen früher wirklich das Aroma für Colagetränke gewonnen. Und heute?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461342/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461342/manifest/',
    },
    {
      name:'Ackerwinde - Convolvulus arvensis',
      shortName:'Ackerwinde',
      source: 'Convolvulus',
      description: 'Wo wächst wohl die Ackerwinde? Sie ist eine in Europa weitverbreitete Pflanzengattung, die tatsächlich neben Äckern, auf Wiesen und Schuttplätzen zu finden ist. Sie wird traditionell als Heilpflanze bei Herzkreislauferkrankungen eingesetzt.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_457144/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_457144/manifest/',
    },
    {
      name:'Muskatnussbaum - Myristica fragrans',
      shortName:'Muskatnussbaum',
      source: 'Myristica_b',
      description: 'Du würdest gern Unmengen von Muskat essen, weil du das Gewürz so lecker findest? Das ist keine gute Idee, denn in sehr hohen Dosen treten beim Genuss von Muskat Rauscherscheinungen und Brechreiz auf. Beruhigend...',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461280/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461280/manifest/',
    },
    {
      name:'Yams - Dioscorea',
      shortName:'Yams',
      source: 'Dioscorea',
      description: 'Hast du schon mal Yams gegessen? Das ist eine tropische Pflanzengattung, deren Teile je nach Pflanzenart als Heilpflanze oder Lebensmittel verwendet werden. Die essbaren Wurzelknollen schmecken ähnlich wie Kartoffeln oder Esskastanien.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461952/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461952/manifest/',
    },
    {
      name:'Muskatnussbaum - Myristica fragrans',
      shortName:'Muskatnussbaum',
      source: 'Myristica_c',
      description: 'Der Muskatnussbaum ist besonders für seine Samen bekannt, die Muskatnüsse. Der Name der Nüsse und des Baumes leiten sich aus dem Französischen ab und bedeuten soviel wie „nach Moschus duftende Nuss“. Und sie schmeckt auch gut, oder?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461280/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461280/manifest/',
    },
    {
      name:'Ebenholzbaum - Diospyros',
      shortName:'Ebenholzbaum',
      source: 'Diospyros_a',
      description: 'Schön wie Ebenholz und genauso lecker? Carl von Linné wählte den Gattungsnamen Diospyros, was soviel heißt wie „göttliche Frucht“. Der Name leitet sich vom Kakibaum ab, der auch zu dieser Gattung gehört und für seine essbaren Kakifrüchte bekannt ist.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461351/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461351/manifest/',
    },
    {
      name:'Ölpalme - Elaeis guineensis',
      shortName:'Ölpalme',
      source: 'Elaeis',
      description: 'Die Ölpalme liefert Palmöl, logisch oder? Das wird aus ihren Früchten gewonnen; der Samen liefert das Palmkernöl. Beide werden in  Lebensmitteln verwendet (z.B. Süßwaren). Problematisch sind die Ölpalmenplantagen, für die oft Regenwald gerodet wird.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461298/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461298/manifest/',
    },
    {
      name:'Lokustbaum - Hymenaea courbaril',
      shortName:'Lokustbaum',
      source: 'Hymenaea_a',
      description: 'Wie viele Namen kann eine Pflanzengattung haben? Die zu den Johannisbrotbaumgewächsen gehörende Gattung Hymenaea hat unzählige, z.B. Animebaum, Südamerikanische Kirsche, Brasilkirsche, Heuschreckenbaum und Lokustbaum. Welcher gefällt dir am besten?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461325/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461325/manifest/',
    },
    {
      name:'Johanniskrautgewächse - Hypericum ascyron',
      shortName:'Johanniskraut',
      source: 'Hypericaceae',
      description: 'Kennst du einen Johannes? Der Name Johanniskraut leitet sich von Johannes dem Täufer (einer Gestalt aus der Bibel) ab, da die Pflanze um den Johannistag (24. Juni) herum blüht. Es wird als Beruhigungsmittel und Antidepressivum verwendet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456951/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456951/manifest/',
    },
    {
      name:'Karitébaum - Butyrospermum parkii',
      shortName:'Karitébaum',
      source: 'Butyrospermum_b',
      description: 'Aber wieso Karitébaum, aber Sheabutter? Das englische „shea“ kommt von „shí“ aus der Bambara-Sprache Malis. In der Wolof-Sprache Senegals heißt der Baum hingegen „Ghariti“. Daraus entstand das französische „karité“ – für den Baum und die Butter.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461349/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461349/manifest/',
    },
    {
      name:'Indigopflanze - Indigofera tinctoria',
      shortName:'Indigopflanze',
      source: 'Indigofera',
      description: 'Schonmal darüber nachgedacht, woher die Jeans ihre Farbe hatte? Die Indigopflanze, die z.B.  in Indien vorkommt, wurde mehrheitlich für die Gewinnung des dunkelblauen Farbstoffs Indigo genutzt. Heute wird dieser Stoff meist synthetisch hergestellt.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461962/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461962/manifest/',
    },
    {
      name:'Schönblühende Kautschukliane - Landolphia comorensis',
      shortName:'Kautschukliane',
      source: 'Landolphia_a',
      description: 'Die Landolphia-Arten sind im tropischen Afrika beheimatet und einige von ihnen sondern Naturkautschuk ab. Wirtschaftlich wird aber fast ausschließlich Kautschuk des Kautschukbaums genutzt, der mit den Landolphia nicht verwandt ist. Verwirrend, oder?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461359/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461359/manifest/',
    },
    {
      name:'Westindisches Mahagoni - Swietenia mahagoni',
      shortName:'Westindisches Mahagoni',
      source: 'Mahagonibaum',
      description: 'Das Westindische Mahagoni kommt im Süden Floridas sowie auf den karibischen Inseln vor und steht auf der Liste stark gefährdeter Arten. Mahagoniholz wird gern für dekorative Furniere beim Möbelbau verwendet. Hast du Mahagonimöbel zu Hause?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_463203/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_463203/manifest/',
    },
    {
      name:'Spanischer Pfeffer - Capsicum annuum',
      shortName:'Spanischer Pfeffer',
      source: 'Capsicum_b',
      description: 'Kein Pfeffer, sondern eine längliche Paprikasorte verbirgt sich hinter Capsicum logum. Die Bandbreite an Schärfegraden in dieser Pflanzenart ist sehr groß und reicht von mildem Gemüsepaprika bis hin zu würzigem Chayennepfeffer und scharfen Chilis.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461353/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461353/manifest/',
    },
    {
      name:'Pfeilwurz - Maranta arundinacea',
      shortName:'Pfeilwurz',
      source: 'Maranta',
      description: 'Pfeilwurz klingt nach einem Fantasy-Roman, oder? Der Name Pfeilwurz bezeichnet sowohl Pflanzenart als auch die übergeordnete Gattung. Das als Arrow Root bezeichnete Stärkemehl wird weltweit als leichtverdauliche Weizenmehlalternative vermarktet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461954/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461954/manifest/',
    },
    {
      name:'Teepflanze - Camellia sinensis',
      shortName:'Teepflanze',
      source: 'Thea',
      description: 'Trinkst du gern Tee? 1753 beschrieb Carl von Linné die Teepflanze erstmals im europäischen Raum unter dem Namen "Thea sinensis". Aus den Blättern der Pflanze wird je nach Stadium und Weiterverarbeitungsart grüner oder schwarzer Tee zubereitet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461270/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461270/manifest/',
    },
    {
      name:'Dessertbanane - Musa sapientium',
      shortName:'Dessertbanane',
      source: 'Musa',
      description: 'Die Dessertbanane stammt aus Südostasien und wurde in religiösen Quellen bereits vor rund 2000 Jahren erwähnt. In Europa ist sie heute eine der meistgegessenen importierten Obstsorten. Wusstest du, dass man sie früher auch „Paradiesfeige“ nannte?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461955/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461955/manifest/',
    },
    {
      name:'Muskatnussbaum - Myristica fragrans',
      shortName:'Muskatnussbaum',
      source: 'Myristica_a',
      description: 'Wie du sicher richtig vermutet hast, leitet sich das Gewürz Muskat vom Muskatnussbaum ab. Dieser vor allem in den Tropen angebaute Baum ist ein immergrünes Gewächs und dessen Samen werden als ebenjene Muskatnüsse bezeichnet. Doch was heißt Muskat?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461280/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461280/manifest/',
    },
    {
      name:'Kolabaum - Cola acuminata',
      shortName:'Kolabaum',
      source: 'Cola_c',
      description: 'Die Nüsse der Kolabäume werden heute nur noch selten für die Gewinnung von Aromen für Colagetränke genutzt. Inzwischen erzeugt man den Geschmack meist chemisch. Sie werden aber noch für Lebensmittelfarbe und Medizin verwendet. Auch gut, oder?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461342/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461342/manifest/',
    },
    {
      name:'Lokustbaum - Hymenaea courbaril',
      shortName:'Lokustbaum',
      source: 'Hymenaea_b',
      description: 'Manche Pflanzenarten haben keinen eindeutigen deutschen Namen, wie die zu den Johannisbrotbaumgewächsen zählende Hymenaea courbaril. Ihre Frucht wird zur Herstellung von Alkohol verwendet, die Rinde wird für Arznei und das Harz für Lacke verwendet.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461325/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461325/manifest/',
    },
    {
      name:'Steinnusspalme - Phytelephas macrocarpa',
      shortName:'Steinnusspalme',
      source: 'Phytelephas',
      description: 'Die auch Elfenbeinpalmen genannten Pflanzen sind in Südamerika beheimatet. Ein Teil des Samens wird in getrocknetem Zustand ebenso hart wie Elfenbein, das sonst die Zahnsubstanz von Elefantenstoßzähnen bezeichnet. Pflanzlicher Elfenbeinersatz also?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461318/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461318/manifest/',
    },
    {
      name:'Piment - Pimenta officinalis',
      shortName:'Piment',
      source: 'Pimenta',
      description: 'Piment (auch Nelkenpfeffer) kommt in Zentralamerika und der Karibik vor. Als Gewürz werden die unreifen Früchte verwendet. Während es in der Karibik ein Bestandteil der Alltagsküche ist, kennst du es vielleicht eher aus der Weihnachtsbäckerei, oder?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461277/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461277/manifest/',
    },
    {
      name:'Spiegelndes Laichkraut - Potamogeton lucens',
      shortName:'Spiegelndes Laichkraut',
      source: 'Potamogetonaceae',
      description: 'Das Spiegelnde Laichkraut ist eine Wasserpflanze, die unter der Wasseroberfläche wächst. Nur die Blüten schauen während der Blütezeit aus dem Wasser hervor, da die Bestäubung durch den Wind erfolgt. Ganz schön praktisch, oder?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456939/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456939/manifest/',
    },
    {
      name:'Echte Dattelpalme - Phoenix dactylifera',
      shortName:'Echte Dattelpalme',
      source: 'Phoenix',
      description: 'Datteln sind heutzutage in unzähligen Snacks und Riegeln, ist dir das aufgefallen? Dabei ist die Echte Dattelpalme eine alte Kulturpflanze, die aus Mesopotamien stammt und deren Nutzung sich sogar bis in die Antike zurückverfolgen lässt.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461946/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461946/manifest/',
    },
    {
      name:'Kampferbaum - Cinnamomum camphora',
      shortName:'Kampferbaum',
      source: 'Cinnamomum',
      description: 'Der Kampferbaum stammt aus Ostasien, wird aber auch in Brasilien angebaut und gilt in einigen Weltregionen als invasive Art. Aus dem Holz des Baumes wird Campheröl gewonnen, das als Medizin genutzt wird. Vielleicht kennst du es vom Erkältungsbad?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_461324/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_461324/manifest/',
    },
    {
      name:'Waldmeister  - Galium odoratum',
      shortName:'Waldmeister',
      source: 'Rubiaceae',
      description: 'Ist das grünes Gift? Nein, überhaupt nicht. Der Waldmeister, auch Maikraut genannt, wird aufgrund seines Geschmacks als Gewürz z.B. für Waldmeisterbowle oder für Sirups genutzt. Heute wird Waldmeisteraroma oft synthetisch hergestellt.',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456904/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456904/manifest/',
    },
    {
      name:'Olivenbaum - Olea europaea',
      shortName:'Olivenbaum',
      source: 'Oleaceae',
      description: 'Der Olivenbaum (Echter Ölbaum) wird im Mittelmeerraum seit mehr als 6000 Jahren als Nutzpflanze angebaut. Aus seinen Oliven-Früchten wird Speiseöl gepresst. Die Oliven sind roh nicht essbar und werden durch Einlegen genießbar gemacht. Lecker, oder?',
      link: 'https://sammlungen.uni-goettingen.de/objekt/record_naniweb_456931/1/-/',
      wiki: 'https://sammlungen.uni-goettingen.de/api/v1/records/record_naniweb_456931/manifest/',
    },
  ],
};
